### ISSUE TITLE
material-ui dependency issue

### ISSUE THREAD

**Issue by Lexpeee** [labd/react-loqate#14]
Do we still use `@material-ui/core` as a dependency? I'm seeing they changed their library to `@mui/material` now.

**Comment by BramKaashoek** [comment]
Hmm, you are right.
Instead of updating to MUI 5 I will just take MUI out. Would be cleaner to not have it in this lib anyway.

**Comment by BramKaashoek** [comment]
Resolved in 1.0.1.
