### ISSUE TITLE
Unable to cleanly handle a misconfigured Loqate account

### ISSUE THREAD

**Issue by jymbob** [labd/react-loqate#15]
You may decide this falls outside your remit, and that's fine.

If a user has entered an invalid API key, or is out of credit, or needs to agree to some updated policies, a packet will be returned in the following format (example - incorrect key):
```
{"Items":
  [
    { "Error":"2",
      "Description":"Unknown key",
      "Cause":"The key you are using to access the service was not found.",
      "Resolution":"Please check that the key is correct. It should be in the form AA11-AA11-AA11-AA11."
    }
  ]
}
```
Currently this will just get passed to the ListItem and displayed. My current workaround is to pass an additional `onError` prop through so I can catch it in my custom ListItem and, in my case, fall back to my standard Address input fields.

What would be really nice is to check on mount if the supplied API key will work. It looks like simply performing a call with no `Text=` is enough to elicit an error response, which responds with Error code 1001 (Text or Container Required) in the case of a successful call, and any other value meaning there is an issue, but I haven't tested all the permutations.

**Comment by BramKaashoek** [comment]
I would rather not do any any extra network requests.

I did make a change so that errors are no longer shown in the Items list, but are instead thrown.
