### ISSUE TITLE
Does this work in React 18

### ISSUE THREAD

**Issue by lindyhopchris** [labd/react-loqate#17]
Hi. I'm using the component as per the docs, but in a React 18 app. I'm seeing the network request come back with results, but no suggestions are displayed. The `<ul>` in the DOM for the address suggestions has no child `<li>` elements, and it is hidden - both of which imply the component is not correctly setting the suggestions even though the network request is successful and contains suggested addresses.

Presumably this component does work in React 17, so I'm wondering whether there's something about the implementation that makes it not work in React 18. Any chance it's been tested in React 18?

**Comment by BramKaashoek** [comment]
We are running this package in production in multiple React 18 projects.
