### ISSUE TITLE
How do I make sure I'm using TLS 1.2 or higher

### ISSUE THREAD

**Issue by TimSmith714** [labd/react-loqate#26]
I've received the notice that Loqate are restricting API connections to HTTPS with TLS of 1.2 or later.
I've confirmed the link I'm using is https but how can I make sure I'm using TLS 1.2 or later?
[Update on Loqate.com](https://www.loqate.com/developers/apis/updating-api-connections/)
Many thanks
Tim

**Comment by BramKaashoek** [comment]
We always use the HTTPS url, so that should not be a problem.
TLS version is browser dependent: https://en.wikipedia.org/wiki/Version_history_for_TLS/SSL_support_in_web_browsers .
As you can see any modern browser will support tls 1.2 or higher
